upgrade to godot 4.4

diff --git a/.github/workflows/export_debug_godot_proj.yml b/.github/workflows/export_debug_godot_proj.yml
--- a/.github/workflows/export_debug_godot_proj.yml
+++ b/.github/workflows/export_debug_godot_proj.yml
@@ -8,29 +8,43 @@ on:
 env:
   GODOT_VERSION: 4.4
   EXPORT_NAME: build-test-debug
-  PROJECT_PATH: .
 
 jobs:
-  pass-env:
-    name: Pass Env
+  pass-var:
+    name: Pass Variables
     runs-on: ubuntu-latest
-    steps:
-      - id: set-output
-        run: echo "godot-version=${GODOT_VERSION}" >> $GITHUB_OUTPUT
-    outputs:
-      godot-version: ${{ steps.set-output.outputs.godot-version }}
-      
-  export-windows:
-    name: Windows Export
-    runs-on: ubuntu-latest
-    needs: [pass-env]
-    container:
-      image: ghcr.io/khrad/godot-builder:${{ needs.pass-env.outputs.godot-version }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           lfs: true
+          submodules: true
+      - name: Pass Godot Version
+        id: pass-version
+        run: echo "godot-version=${GODOT_VERSION}" >> $GITHUB_OUTPUT
+      - name: Pass Platforms
+        id: pass-platforms
+        run: |
+          cd $(find . -name "project.godot" | grep -v "godot.cpp" | xargs dirname)
+          platforms=$(grep "platform=" export_presets.cfg | sed -zr 's@(platform="| )@.@g;s@"\n@@g')
+          echo "platforms=$platforms" >> $GITHUB_OUTPUT
+    outputs:
+      godot-version: ${{ steps.pass-version.outputs.godot-version }}
+      platforms: ${{ steps.pass-platforms.outputs.platforms }}
+
+  export-windows:
+    name: Windows Export
+    runs-on: ubuntu-latest
+    needs: [pass-var]
+    if: contains(needs.pass-var.outputs.platforms, 'Windows')
+    container:
+      image: ghcr.io/khrad/godot-builder:${{ needs.pass-var.outputs.godot-version }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          lfs: true
+          submodules: true
       - name: Setup
         run: |
           mkdir -v -p ~/.local/share/godot
@@ -51,8 +65,8 @@ jobs:
         run: |
           mkdir -v -p build/windows
           EXPORT_DIR="$(readlink -f build)"
-          cd $PROJECT_PATH
-          godot --headless --verbose --export-debug "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
+          cd $(find . -name "project.godot" | grep -v "godot.cpp" | xargs dirname)
+          godot --headless --verbose --export-debug "Windows Desktop" "$EXPORT_DIR/windows/${EXPORT_NAME}.exe"
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
@@ -62,14 +76,16 @@ jobs:
   export-linux:
     name: Linux Export
     runs-on: ubuntu-latest
-    needs: [pass-env]
+    needs: [pass-var]
+    if: contains(needs.pass-var.outputs.platforms, 'Linux')
     container:
-      image: ghcr.io/khrad/godot-builder:${{needs.pass-env.outputs.godot-version}}
+      image: ghcr.io/khrad/godot-builder:${{needs.pass-var.outputs.godot-version}}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           lfs: true
+          submodules: true
       - name: Setup
         run: |
           mkdir -v -p ~/.local/share/godot
@@ -88,8 +104,8 @@ jobs:
         run: |
           mkdir -v -p build/linux
           EXPORT_DIR="$(readlink -f build)"
-          cd $PROJECT_PATH
-          godot --headless --verbose --export-debug "Linux/X11" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
+          cd $(find . -name "project.godot" | grep -v "godot.cpp" | xargs dirname)
+          godot --headless --verbose --export-debug "Linux" "$EXPORT_DIR/linux/${EXPORT_NAME}.x86_64"
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
@@ -99,59 +115,63 @@ jobs:
   export-web:
     name: Web Export
     runs-on: ubuntu-latest
-    needs: [pass-env]
+    needs: [pass-var]
+    if: contains(needs.pass-var.outputs.platforms, 'Web')
     container:
-      image: ghcr.io/khrad/godot-builder:${{needs.pass-env.outputs.godot-version}}
+      image: ghcr.io/khrad/godot-builder:${{needs.pass-var.outputs.godot-version}}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           lfs: true
+          submodules: true
       - name: Setup
+        id: setup
         run: |
           mkdir -v -p ~/.local/share/godot
           mv /root/.local/share/godot/export_templates ~/.local/share/godot/export_templates
           
           isDotnet=$(find . -name "project.godot" | grep -v "godot-cpp" | xargs cat | { grep "dotnet" || true; })          
           if [ -n "$isDotnet" ]; then
-              echo "2" | update-alternatives --config godot >> /dev/null
+              #echo "2" | update-alternatives --config godot >> /dev/null
+              echo "godot from current version can't export to WEB if mono"
+              echo "skip_web_build=true" >> $GITHUB_OUTPUT
+              exit 0
           fi
+          
+          echo "skip_web_build=false" >> $GITHUB_OUTPUT
           
           hasExtension=$(find . -name "godot-cpp")
           if [ -n "$hasExtension" ]; then
               scons platform=linux target=template_debug
           fi
       - name: Web Build
+        if: ${{ steps.setup.outputs.skip_web_build == 'false'}}
         run: |
           mkdir -v -p build/web
           EXPORT_DIR="$(readlink -f build)"
-          cd $PROJECT_PATH
-          godot --headless --verbose --export-debug "Web" "$EXPORT_DIR/web/index.html"
+          cd $(find . -name "project.godot" | grep -v "godot.cpp" | xargs dirname)
+          godot --headless --verbose --export-debug "Web" "$EXPORT_DIR/web/${EXPORT_NAME}.html"
       - name: Upload Artifact
+        if: ${{ steps.setup.outputs.skip_web_build == 'false'}}
         uses: actions/upload-artifact@v4
         with:
           name: web
           path: build/web
-      - name: Install rsync 📚
-        run: |
-          apt-get update && apt-get install -y rsync
-      - name: Deploy to GitHub Pages 🚀
-        uses: JamesIves/github-pages-deploy-action@releases/v4
-        with:
-          branch: gh-pages # The branch the action should deploy to.
-          folder: build/web # The folder the action should deploy.
-
+          
   export-mac:
     name: Mac Export
     runs-on: ubuntu-latest
-    needs: [pass-env]
+    needs: [pass-var]
+    if: contains(needs.pass-var.outputs.platforms, 'macOS')
     container:
-      image: ghcr.io/khrad/godot-builder:${{needs.pass-env.outputs.godot-version}}
+      image: ghcr.io/khrad/godot-builder:${{needs.pass-var.outputs.godot-version}}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           lfs: true
+          submodules: true
       - name: Setup
         run: |
           mkdir -v -p ~/.local/share/godot
@@ -170,24 +190,35 @@ jobs:
         run: |
           mkdir -v -p build/mac
           EXPORT_DIR="$(readlink -f build)"
-          cd $PROJECT_PATH
-          godot --headless --verbose --export-debug "macOS" "$EXPORT_DIR/mac/$EXPORT_NAME.zip"
+          cd $(find . -name "project.godot" | grep -v "godot.cpp" | xargs dirname)
+          
+          hasEtcConfig=$(cat project.godot | { grep "import_etc2_astc" || true; })
+          if [ -n "$hasEtcConfig" ]; then
+              sed 's@textures/vram_compression/import_etc2_astc=".*"@textures/vram_compression/import_etc2_astc=true@g' -i project.godot
+          else
+              sed 's@\[rendering\]@\[rendering\]\ntextures/vram_compression/import_etc2_astc=true@g' -i project.godot
+          fi
+          
+          godot --headless --verbose --export-debug "macOS" "$EXPORT_DIR/mac/${EXPORT_NAME}.zip"
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
           name: mac
           path: build/mac
+          
   export-android:
     name: Android Export
     runs-on: ubuntu-latest
-    needs: [pass-env]
+    needs: [pass-var]
+    if: contains(needs.pass-var.outputs.platforms, 'Android')
     container:
-      image: ghcr.io/khrad/godot-builder:${{needs.pass-env.outputs.godot-version}}
+      image: ghcr.io/khrad/godot-builder:${{needs.pass-var.outputs.godot-version}}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           lfs: true
+          submodules: true
       - name: Setup
         run: |
           mkdir -v -p ~/.local/share/godot
@@ -196,6 +227,7 @@ jobs:
           isDotnet=$(find . -name "project.godot" | grep -v "godot-cpp" | xargs cat | { grep "dotnet" || true; })          
           if [ -n "$isDotnet" ]; then
               echo "2" | update-alternatives --config godot >> /dev/null
+              ln -nsf /opt/godot/mono/gradle /opt/godot/gradle
           fi
           
           hasExtension=$(find . -name "godot-cpp")
@@ -206,8 +238,19 @@ jobs:
         run: |
           mkdir -v -p build/android
           EXPORT_DIR="$(readlink -f build)"
-          cd $PROJECT_PATH
-          godot --headless --verbose --export-debug "Android" "$EXPORT_DIR/android/$EXPORT_NAME.apk"
+          cd $(find . -name "project.godot" | grep -v "godot.cpp" | xargs dirname)
+          sed 's@gradle_build/use_gradle_build=.*@gradle_build/use_gradle_build=true@g' -i export_presets.cfg
+          sed 's@gradle_build/gradle_build_directory=.*@gradle_build/gradle_build_directory="/opt/godot/gradle"@g' -i export_presets.cfg
+          sed 's@gradle_build/export_format=.*@gradle_build/export_format=1@g' -i export_presets.cfg
+          
+          hasEtcConfig=$(cat project.godot | { grep "import_etc2_astc" || true; })
+          if [ -n "$hasEtcConfig" ]; then
+              sed 's@textures/vram_compression/import_etc2_astc=".*"@textures/vram_compression/import_etc2_astc=true@g' -i project.godot
+          else
+              sed 's@\[rendering\]@\[rendering\]\ntextures/vram_compression/import_etc2_astc=true@g' -i project.godot
+          fi
+          
+          godot --headless --verbose --export-debug "Android" "$EXPORT_DIR/android/${EXPORT_NAME}.aab"
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
